### ISSUE TITLE
If you play the game, when it is blacks turn, there are exceptions and you need to double klick

### ISSUE THREAD

**Issue by BaconCookie** [HoboOthello/HoboOthello#15]
die Nullpointer Exc. kommen jetzt wenn schwarz dran ist. man klickt auf ein blaues feld, muss danach noch mal klicken damit der stein auch gesetzt wird. wo man das 2e mal klickt ist scheinbar egal

**Comment by linuxluigi** [comment]
look like a error in KI Level 2 & 3
KI Level 1 works fine

**Comment by linuxluigi** [comment]
Example in KI Level2 I got the follow error message

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 6
	at de.htw_berlin.HoboOthello.Core.Board.isCornerField(Board.java:74)
	at de.htw_berlin.HoboOthello.KI.KI.pickCornerOrSideFieldFromList(KI.java:106)
	at de.htw_berlin.HoboOthello.KI.KI.setMove(KI.java:42)
	at de.htw_berlin.HoboOthello.Core.Game.setTurn(Game.java:112)

**Comment by linuxluigi** [comment]
bug in listPossibleFieldsNotTooCloseToBorder()

https://github.com/HoboOthello/HoboOthello/blob/master/src/main/java/de/htw_berlin/HoboOthello/KI/KI.java#L220

**Comment by linuxluigi** [comment]
it take to much time, we will only push in the future our builds to github

**Comment by BaconCookie** [comment]
Steffen Samstag KI level 3 debugging?
