### ISSUE TITLE
KI Level 2 - NullPointerException

### ISSUE THREAD

**Issue by linuxluigi** [HoboOthello/HoboOthello#9]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.htw_berlin.HoboOthello.KI.KI.listPossibleMoves(KI.java:66)

**Comment by linuxluigi** [comment]
With KI Level 3
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.htw_berlin.HoboOthello.KI.KI.listPossibleMoves(KI.java:64)

**Comment by linuxluigi** [comment]
fixed
